### ISSUE TITLE
a fork is the official publisher but this makes things "unclear"

### ISSUE THREAD

**Issue by tngTUDOR** [polca/premise#10]
I have two comments on the fact that the fork from @romainsacchi  is the official publisher of the package: installation and issue creation.

### 1. Installation nightmare

The package is officially published from a fork (the one of @romainsacchi )
The documentation clearly says that to install the package, one has 2 options:

* install with pip *from git*  from the fork of @romainsacchi repository (despite a package is published at pypi -> https://pypi.org/project/rmnd-lca/ )
* install with conda, from romainsacchi's channel

In my particular case, I use install brightway2 from (a virtual environment created with) conda, and I would rather have a "conda coherent" environment: as many packages as possible installed with conda, and only use pip as last option. 

right now [2020-11-16] , pypi seems to have (semantic) version 0.1.6 of rmnd-lca package online, while the conda package is being built nightly and uses calendar labels (latest being -> 2020.11.13).

I'm more in favor of semantic versioning, but I think that at least the documentation should say a bit more about all this.
For example, if the developers intend to keep both packages, explain which is the intended use of the conda package (maybe, for edge, development builds) vs. the intended use of the pypi package: stable, proven use.

### 2. Issue creation

Issues are filed against the original repository, because it's impossible to file them against the one of the fork (I don't know if this can be changed).

**Comment by Loisel** [comment]
Yeah this is unfortunate, I agree. Afaik there is no possibility to move the *root* project to another user. One would have to recreate the thing. What's your stance @romainsacchi ?

**Comment by romainsacchi** [comment]
@Loisel: I think we probably should have you managing the CI and publishing, and I would, as a result, stop working on my fork to have one consistent and updated base. Initially, I developed on my fork and published from there because I did not have writing access to yours. If you do not feel like it, we could do the opposite, close this repo and have everything on mine.

**Comment by tngTUDOR** [comment]
I'm not sure how it all works, but you could try to have @Loisel  [transfer the repo](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository) to  @romainsacchi 
*but* the fork situation must certainly be figured out first ( I mean, _What happens when there is a transfer but the recipient has a fork of the repo being transferred ?_)
I guess, that if you go for a  "transfer", maybe @Loisel should first merge all the work inside the fork of @romainsacchi , and then organise the transfer. 

This is only my opinion ;)

**Comment by romainsacchi** [comment]
OK, the repo has been transferred, so it should be (a bit) clearer hopefully now -)
