### ISSUE TITLE
pip install is failing for Premise

### ISSUE THREAD

**Issue by tapajyoti-ghosh** [polca/premise#109]
pip install premise==1.5.7
ERROR: Could not find a version that satisfies the requirement premise==1.5.7 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.3.0, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.8, 0.3.9, 0.4.0, 0.4.1, 0.4.2, 0.4.4, 0.4.5, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.5, 1.0.6, 1.0.7, 1.0.8)
ERROR: No matching distribution found for premise==1.5.7

pip install premise installs v1.0.8

**Comment by romainsacchi** [comment]
Hi @tjlca, I suggest to install v.1.6.1
```pip install premise==1.6.1```

**Comment by tapajyoti-ghosh** [comment]
(liaison)
```
tghosh$ pip install premise==1.6.1
ERROR: Could not find a version that satisfies the requirement premise==1.6.1 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.3.0, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.8, 0.3.9, 0.4.0, 0.4.1, 0.4.2, 0.4.4, 0.4.5, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.5, 1.0.6, 1.0.7, 1.0.8)
ERROR: No matching distribution found for premise==1.6.1
```

@romainsacchi

**Comment by romainsacchi** [comment]
I don't know.
`premise 1.6.1` does exist and [is published on Pypi](https://pypi.org/project/premise/).
I just tried it myself and it works fine.
You might have an issue with your package manager.
Try in a new environment?

**Comment by romainsacchi** [comment]
BTW, there's now `1.6.2`.

**Comment by tapajyoti-ghosh** [comment]
VPN issue on our end@ Thanks for the help. Got it resolved.
