### ISSUE TITLE
Documentation about remind output files directory

### ISSUE THREAD

**Issue by tngTUDOR** [polca/premise#11]
The documentation mentions:

(in the *Requirements* section)
> REMIND IAM output files come with the library ("xxx.mif" and "GAINS emission factors.csv") and are located by default in the subdirectory "/data/Remind output files". A file path can be specified to fetch the REMIND IAM output files elsewhere on your computer.

(in the *How to use it?* section)
> Note that, by default, the library will look for REMIND output files ("xxx.mif" files and "GAINS emission factors.csv") in the "data/Remind output files" subdirectory. If those are not located there, you need to specify the path to the correct directory, as such::

but the actual location inside the rmnd-lca package is:

`data/remind_output_files/`

This is a minor cosmetic issue, but I see that the ".gitignore" file

**Comment by romainsacchi** [comment]
That should be fixed now, thanks.
