### ISSUE TITLE
Electricity production from lignite power plants in USA have fuel input as lignite mine operation and not market for lignite

### ISSUE THREAD

**Issue by tapajyoti-ghosh** [polca/premise#130]
electricity production, at lignite-fired IGCC power plant
electricity production, at lignite-fired power plant, post, pipeline 200km, storage 1000m
electricity production, at lignite-fired IGCC power plant, pre, pipeline 200km, storage 1000m
electricity production, at lignite-fired power plant, oxy, pipeline 200km, storage 1000m

Is there any specific reason why they were linked with lignite mine operation and not market for lignite? The original ecoinvent lignite elec production links to market for lignite.

**Comment by romainsacchi** [comment]
Done. It will be part of the next release.
