### ISSUE TITLE
Problem with the pip install of premise version 1.8.1

### ISSUE THREAD

**Issue by MaximeAgez** [polca/premise#132]
Hi. Tried to install premise v1.8.1 through pip. Installation works. But whenever I try to call `from premise import *'` I get the following error.

[Error.pdf](https://github.com/polca/premise/files/13269546/Error.pdf)

**Comment by cmutel** [comment]
THe error is

```python
11 import warnings
---> 13 from jsonschema._format import FormatChecker
14 from jsonschema._types import TypeChecker
15 from jsonschema.exceptions import SchemaError, ValidationError
File ~\AppData\Local\anaconda3new\envs\premisever\lib\site-packages\json schema\_format.py:503
497 with suppress(ImportError): 
498 import isoduration
500 @_checks_drafts(
501
502
--> 503
504 )
draft201909="duration",
draft202012="duration",
raises=isoduration.DurationParsingException,
505 506 507
def is_duration(instance: object) -> bool: if not isinstance(instance, str):
return True
AttributeError: module 'isoduration' has no attribute 'DurationParsingException'
```

However, the `isoduration` library has had 'DurationParsingException' in its `__init__.py` for [at least three years](https://github.com/bolsote/isoduration/blob/master/src/isoduration/__init__.py).

In the same issue [in another repo](https://github.com/napari/napari/issues/6220), they suggested reinstalling `isoduration`. Maybe that helps?

**Comment by MaximeAgez** [comment]
Updating isoduration solved the issue indeed :)
