### ISSUE TITLE
`constructive_geometries` compatibility problems

### ISSUE THREAD

**Issue by marcosdbw** [polca/premise#135]
Hello all.
I have just installed premise (v. 1.8.1), via pip install premise
When I try to import premise on my notebook, the following message appears.
Do you know how to solve this issue?
Thank you.

from premise import *

US-PR not found in regex
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[1], line 1
----> 1 from premise import *

File ~\miniconda3\envs\bw2\lib\site-packages\premise\__init__.py:5
      1 __all__ = ("NewDatabase", "clear_cache", "get_regions_definition")
      2 __version__ = (1, 8, 1)
----> 5 from .ecoinvent_modification import NewDatabase
      6 from .utils import clear_cache, get_regions_definition

File ~\miniconda3\envs\bw2\lib\site-packages\premise\ecoinvent_modification.py:23
     20 import yaml
     22 from . import __version__
---> 23 from .cement import _update_cement
     24 from .clean_datasets import DatabaseCleaner
     25 from .data_collection import IAMDataCollection

File ~\miniconda3\envs\bw2\lib\site-packages\premise\cement.py:14
     11 from collections import defaultdict
     13 from .logger import create_logger
---> 14 from .transformation import BaseTransformation, Dict, IAMDataCollection, List, np, ws
     16 logger = create_logger("cement")
     19 def _update_cement(scenario, version, system_model, modified_datasets, cache=None):

File ~\miniconda3\envs\bw2\lib\site-packages\premise\transformation.py:22
     20 from _operator import itemgetter
     21 from constructive_geometries import resolved_row
---> 22 from wurst import reference_product, rescale_exchange
     23 from wurst import searching as ws
     24 from wurst import transformations as wt

File ~\miniconda3\envs\bw2\lib\site-packages\wurst\__init__.py:69
     54 from .filesystem import create_log, create_dir
     55 from .searching import (
     56     best_geo_match,
     57     biosphere,
   (...)
     67     technosphere,
     68 )
---> 69 from .transformations import (
     70     change_exchanges_by_constant_factor,
     71     copy_to_new_location,
     72     default_global_location,
     73     delete_zero_amount_exchanges,
     74     empty_market_dataset,
     75     relink_technosphere_exchanges,
     76     rescale_exchange,
     77 )
     78 from .geo import geomatcher
     79 from constructive_geometries import resolved_row

File ~\miniconda3\envs\bw2\lib\site-packages\wurst\transformations\__init__.py:3
      1 from .activity import change_exchanges_by_constant_factor
      2 from .cleaning import delete_zero_amount_exchanges, empty_market_dataset
----> 3 from .geo import (
      4     copy_to_new_location,
      5     default_global_location,
      6     relink_technosphere_exchanges,
      7 )
      8 from .uncertainty import rescale_exchange

File ~\miniconda3\envs\bw2\lib\site-packages\wurst\transformations\geo.py:3
      1 from .. import log
      2 from ..errors import InvalidLink
----> 3 from ..geo import geomatcher
      4 from ..searching import reference_product, get_many, equals, get_one
      5 from .uncertainty import rescale_exchange

File ~\miniconda3\envs\bw2\lib\site-packages\wurst\geo.py:7
      3 from constructive_geometries import Geomatcher
      6 geomatcher = Geomatcher()
----> 7 geomatcher.add_definitions(IMAGE_TOPOLOGY, "IMAGE", relative=True)
      8 geomatcher.add_definitions(REMIND_TOPOLOGY, "REMIND", relative=True)

File ~\miniconda3\envs\bw2\lib\site-packages\constructive_geometries\geomatcher.py:290, in Geomatcher.add_definitions(self, data, namespace, relative)
    287     self.faces.update(set.union(*data.values()))
    288 else:
    289     self.topology.update(
--> 290         {
    291             (namespace, k): set.union(*[self[o] for o in v])
    292             for k, v in data.items()
    293         }
    294     )

File ~\miniconda3\envs\bw2\lib\site-packages\constructive_geometries\geomatcher.py:291, in <dictcomp>(.0)
    287     self.faces.update(set.union(*data.values()))
    288 else:
    289     self.topology.update(
    290         {
--> 291             (namespace, k): set.union(*[self[o] for o in v])
    292             for k, v in data.items()
    293         }
    294     )

File ~\miniconda3\envs\bw2\lib\site-packages\constructive_geometries\geomatcher.py:291, in <listcomp>(.0)
    287     self.faces.update(set.union(*data.values()))
    288 else:
    289     self.topology.update(
    290         {
--> 291             (namespace, k): set.union(*[self[o] for o in v])
    292             for k, v in data.items()
    293         }
    294     )

File ~\miniconda3\envs\bw2\lib\site-packages\constructive_geometries\geomatcher.py:81, in Geomatcher.__getitem__(self, key)
     79 if key == "RoW" and "RoW" not in self.topology:
     80     return set()
---> 81 return self.topology[self._actual_key(key)]

File ~\miniconda3\envs\bw2\lib\site-packages\constructive_geometries\geomatcher.py:114, in Geomatcher._actual_key(self, key)
    111             print("Geomatcher: Used '{}' for '{}'".format(new, key))
    112         return new
--> 114 raise KeyError("Can't find location: {}.".format(key))

KeyError: "Can't find location: US-PR."

Click to add a cell.

**Comment by cmutel** [comment]
`constructive_geometries.geomatcher` now has a [`backwards_compatible` mode](https://github.com/ecoinvent/constructive_geometries/issues/12). Looks like this is a problem with `wurst`:

```python
File ~\miniconda3\envs\bw2\lib\site-packages\wurst\geo.py:7
3 from constructive_geometries import Geomatcher
6 geomatcher = Geomatcher()
----> 7 geomatcher.add_definitions(IMAGE_TOPOLOGY, "IMAGE", relative=True)
8 geomatcher.add_definitions(REMIND_TOPOLOGY, "REMIND", relative=True)
```

But this is already changed in [`wurst`](https://github.com/polca/wurst/commit/56d743689036de787b4cd36de0433f332bac9018), it just needs a new release.

**Comment by cmutel** [comment]
Fixed in `wurst` 0.3.5, released 2023-11-27.

**Comment by marcosdbw** [comment]
Thanks, @cmutel 
I have installed it (via pip install wurst==0.3.5)
and now I have a message related to another region

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[1], line 1
----> 1 from premise import *

File ~\miniconda3\envs\bw2\lib\site-packages\premise\__init__.py:5
      1 __all__ = ("NewDatabase", "clear_cache", "get_regions_definition")
      2 __version__ = (1, 8, 1)
----> 5 from .ecoinvent_modification import NewDatabase
      6 from .utils import clear_cache, get_regions_definition

File ~\miniconda3\envs\bw2\lib\site-packages\premise\ecoinvent_modification.py:23
     20 import yaml
     22 from . import __version__
---> 23 from .cement import _update_cement
     24 from .clean_datasets import DatabaseCleaner
     25 from .data_collection import IAMDataCollection

File ~\miniconda3\envs\bw2\lib\site-packages\premise\cement.py:14
     11 from collections import defaultdict
     13 from .logger import create_logger
---> 14 from .transformation import BaseTransformation, Dict, IAMDataCollection, List, np, ws
     16 logger = create_logger("cement")
     19 def _update_cement(scenario, version, system_model, modified_datasets, cache=None):

File ~\miniconda3\envs\bw2\lib\site-packages\premise\transformation.py:22
     20 from _operator import itemgetter
     21 from constructive_geometries import resolved_row
---> 22 from wurst import reference_product, rescale_exchange
     23 from wurst import searching as ws
     24 from wurst import transformations as wt

File ~\miniconda3\envs\bw2\lib\site-packages\wurst\__init__.py:69
     54 from .filesystem import create_log, create_dir
     55 from .searching import (
     56     best_geo_match,
     57     biosphere,
   (...)
     67     technosphere,
     68 )
---> 69 from .transformations import (
     70     change_exchanges_by_constant_factor,
     71     copy_to_new_location,
     72     default_global_location,
     73     delete_zero_amount_exchanges,
     74     empty_market_dataset,
     75     relink_technosphere_exchanges,
     76     rescale_exchange,
     77 )
     78 from .geo import geomatcher
     79 from constructive_geometries import resolved_row

File ~\miniconda3\envs\bw2\lib\site-packages\wurst\transformations\__init__.py:3
      1 from .activity import change_exchanges_by_constant_factor
      2 from .cleaning import delete_zero_amount_exchanges, empty_market_dataset
----> 3 from .geo import (
      4     copy_to_new_location,
      5     default_global_location,
      6     relink_technosphere_exchanges,
      7 )
      8 from .uncertainty import rescale_exchange

File ~\miniconda3\envs\bw2\lib\site-packages\wurst\transformations\geo.py:3
      1 from .. import log
      2 from ..errors import InvalidLink
----> 3 from ..geo import geomatcher
      4 from ..searching import reference_product, get_many, equals, get_one
      5 from .uncertainty import rescale_exchange

File ~\miniconda3\envs\bw2\lib\site-packages\wurst\geo.py:6
      2 from .REMIND import REMIND_TOPOLOGY
      3 from constructive_geometries import Geomatcher
----> 6 geomatcher = Geomatcher(backwards_compatible=True)
      7 geomatcher.add_definitions(IMAGE_TOPOLOGY, "IMAGE", relative=True)
      8 geomatcher.add_definitions(REMIND_TOPOLOGY, "REMIND", relative=True)

File ~\miniconda3\envs\bw2\lib\site-packages\constructive_geometries\geomatcher.py:61, in Geomatcher.__init__(self, topology, default_namespace, use_coco, backwards_compatible)
     58     else:
     59         return ("ecoinvent", x)
---> 61 cg = ConstructiveGeometries(backwards_compatible=backwards_compatible)
     62 self.topology = {
     63     ns(x): set(y) for x, y in cg.data.items() if x != "__all__"
     64 }
     65 self["GLO"] = reduce(set.union, self.topology.values())

File ~\miniconda3\envs\bw2\lib\site-packages\constructive_geometries\cg.py:86, in ConstructiveGeometries.__init__(self, backwards_compatible)
     84 self.load_definitions()
     85 if backwards_compatible:
---> 86     self.add_backward_compatible_definitions()

File ~\miniconda3\envs\bw2\lib\site-packages\constructive_geometries\cg.py:107, in ConstructiveGeometries.add_backward_compatible_definitions(self)
    105 def add_backward_compatible_definitions(self) -> None:
    106     for key, value in COMPATIBILITY.items():
--> 107         self.data[key] = self.data[value]
    108         self.locations.add(key)
    109     for key in EMPTY:

KeyError: 'Europe, without Russia and Türkiye'

**Comment by cmutel** [comment]
Weird... that is [definitely present](https://github.com/ecoinvent/constructive_geometries/blob/master/constructive_geometries/data/faces.json#L21954). Will investigate let.

**Comment by romainsacchi** [comment]
Hi @cmutel, another user has reported this issue. 
Could it be a decoding issue/something to do with special characters such as "ü"? Could it be that, even though utf-8 should be used to open the file, since it is not specified, another encoding is used?
I do not have this issue though, which is strange.

**Comment by romainsacchi** [comment]
I think the issue comes from the fact that `Europe, without Russia and Türkiye` is not listed in constructive_geometries/compatibility.py [This PR](https://github.com/ecoinvent/constructive_geometries/pull/15) should fix that.

**Comment by marcosdbw** [comment]
Yes, @romainsacchi , it solved the issue, thanks.
But then when I tried to load it (premise 1.8.2.dev1), I got the following error:

---------------------------------------------------------------------------
SyntaxError                               Traceback (most recent call last)
    [... skipping hidden 1 frame]

Cell In[1], line 1
----> 1 from premise import*

File ~\miniconda3\envs\bw2\lib\site-packages\premise\__init__.py:5
      2 __version__ = (1, 8, 2, "dev1")
----> 5 from .ecoinvent_modification import NewDatabase
      6 from .utils import clear_cache, get_regions_definition

File ~\miniconda3\envs\bw2\lib\site-packages\premise\ecoinvent_modification.py:23
     22 from . import __version__
---> 23 from .biomass import _update_biomass
     24 from .cement import _update_cement

File ~\miniconda3\envs\bw2\lib\site-packages\premise\biomass.py:12
     10 import yaml
---> 12 from .export import biosphere_flows_dictionary
     13 from .filesystem_constants import VARIABLES_DIR

File ~\miniconda3\envs\bw2\lib\site-packages\premise\export.py:30
     29 from .filesystem_constants import DATA_DIR
---> 30 from .inventory_imports import get_correspondence_bio_flows
     31 from .transformation import BaseTransformation

File ~\miniconda3\envs\bw2\lib\site-packages\premise\inventory_imports.py:19
     18 from prettytable import PrettyTable
---> 19 from wurst import searching as ws
     21 from .clean_datasets import remove_categories, remove_uncertainty

File ~\miniconda3\envs\bw2\lib\site-packages\wurst\__init__.py:69
     55 from .searching import (
     56     best_geo_match,
     57     biosphere,
   (...)
     67     technosphere,
     68 )
---> 69 from .transformations import (
     70     change_exchanges_by_constant_factor,
     71     copy_to_new_location,
     72     default_global_location,
     73     delete_zero_amount_exchanges,
     74     empty_market_dataset,
     75     relink_technosphere_exchanges,
     76     rescale_exchange,
     77 )
     78 from .geo import geomatcher

File ~\miniconda3\envs\bw2\lib\site-packages\wurst\transformations\__init__.py:3
      2 from .cleaning import delete_zero_amount_exchanges, empty_market_dataset
----> 3 from .geo import (
      4     copy_to_new_location,
      5     default_global_location,
      6     relink_technosphere_exchanges,
      7 )
      8 from .uncertainty import rescale_exchange

File ~\miniconda3\envs\bw2\lib\site-packages\wurst\transformations\geo.py:3
      2 from ..errors import InvalidLink
----> 3 from ..geo import geomatcher
      4 from ..searching import reference_product, get_many, equals, get_one

File ~\miniconda3\envs\bw2\lib\site-packages\wurst\geo.py:3
      2 from .REMIND import REMIND_TOPOLOGY
----> 3 from constructive_geometries import Geomatcher
      6 geomatcher = Geomatcher(backwards_compatible=True)

File ~\miniconda3\envs\bw2\lib\site-packages\constructive_geometries\__init__.py:10
      7 __version__ = "0.9.4"
---> 10 from .cg import ConstructiveGeometries
     11 from .geomatcher import Geomatcher, resolved_row

File ~\miniconda3\envs\bw2\lib\site-packages\constructive_geometries\cg.py:13
     11 import wrapt
---> 13 from .compatibility import COMPATIBILITY, EMPTY
     15 try:

SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xfc in position 28: invalid start byte (compatibility.py, line 16)

During handling of the above exception, another exception occurred:

UnicodeDecodeError                        Traceback (most recent call last)
    [... skipping hidden 1 frame]

File ~\miniconda3\envs\bw2\lib\site-packages\IPython\core\interactiveshell.py:2114, in InteractiveShell.showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2109     return
   2111 if issubclass(etype, SyntaxError):
   2112     # Though this won't be called by syntax errors in the input
   2113     # line, there may be SyntaxError cases with imported code.
-> 2114     self.showsyntaxerror(filename, running_compiled_code)
   2115 elif etype is UsageError:
   2116     self.show_usage_error(value)

File ~\miniconda3\envs\bw2\lib\site-packages\IPython\core\interactiveshell.py:2202, in InteractiveShell.showsyntaxerror(self, filename, running_compiled_code)
   2200 # If the error occurred when executing compiled code, we should provide full stacktrace.
   2201 elist = traceback.extract_tb(last_traceback) if running_compiled_code else []
-> 2202 stb = self.SyntaxTB.structured_traceback(etype, value, elist)
   2203 self._showtraceback(etype, value, stb)

File ~\miniconda3\envs\bw2\lib\site-packages\IPython\core\ultratb.py:1472, in SyntaxTB.structured_traceback(self, etype, value, elist, tb_offset, context)
   1468 if isinstance(value, SyntaxError) \
   1469         and isinstance(value.filename, str) \
   1470         and isinstance(value.lineno, int):
   1471     linecache.checkcache(value.filename)
-> 1472     newtext = linecache.getline(value.filename, value.lineno)
   1473     if newtext:
   1474         value.text = newtext

File ~\miniconda3\envs\bw2\lib\linecache.py:30, in getline(filename, lineno, module_globals)
     26 def getline(filename, lineno, module_globals=None):
     27     """Get a line for a Python source file from the cache.
     28     Update the cache if it doesn't contain an entry for this file already."""
---> 30     lines = getlines(filename, module_globals)
     31     if 1 <= lineno <= len(lines):
     32         return lines[lineno - 1]

File ~\miniconda3\envs\bw2\lib\linecache.py:46, in getlines(filename, module_globals)
     43         return cache[filename][2]
     45 try:
---> 46     return updatecache(filename, module_globals)
     47 except MemoryError:
     48     clearcache()

File ~\miniconda3\envs\bw2\lib\linecache.py:137, in updatecache(filename, module_globals)
    135 try:
    136     with tokenize.open(fullname) as fp:
--> 137         lines = fp.readlines()
    138 except OSError:
    139     return []

File ~\miniconda3\envs\bw2\lib\codecs.py:322, in BufferedIncrementalDecoder.decode(self, input, final)
    319 def decode(self, input, final=False):
    320     # decode input (taking the buffer into account)
    321     data = self.buffer + input
--> 322     (result, consumed) = self._buffer_decode(data, self.errors, final)
    323     # keep undecoded input until the next call
    324     self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 547: invalid start byte

**Comment by cmutel** [comment]
@marcosdbw I think the unicode error came from Romain's patch. The `constructive_geometries` CI tests were broken, but should work now, and they don't show this error.

The character mentioned is, I think, from the [Windows encoding `Windows-1252`](https://bytetool.web.app/en/ascii/code/0xfc/), and isn't valid utf-8.

**Comment by marcosdbw** [comment]
thanks for the update, @cmutel

**Comment by romainsacchi** [comment]
@marcosdbw this issue is now fixed by updating `constructive_geometries` to `0.9.5`.

**Comment by marcosdbw** [comment]
Thanks, @romainsacchi !
