### ISSUE TITLE
Water amount set to zero in biofuel crops datasets

### ISSUE THREAD

**Issue by dsavelief** [polca/premise#136]
Hello,

in the additional inventories from lci-biofuels.xlsx the biosphere exchanges for `Water, unspecified natural origin` have been set to zero (at least since v.1.8.1).

For instance, `Farming and supply of switchgrass` requires 0.708 cubic meters of `Water, unspecified natural origin` in premise v.1.5.7, but this amount is set to 0 in the recent versions. This is the case for a lot of (if not all) crops cultivation datasets .

Is this a modeling choice ?

Thanks,
Dominique

**Comment by romainsacchi** [comment]
Hello @dsavelief ,

yes, I initially added this water amount but retracted afterwards in 1.8.
These water amounts correspond to **green water** consumption (from precipitation held in soil). And I realized that this is usually not considered in the rest of the datasets in ecoinvent -- only blue water from irrigation is, usually. That is why I thought it was probably wrong to have it there, specifically when comparing it with other crop datasets of ecoinvent, which do not account for it (and those are very large amounts of water).

**Comment by romainsacchi** [comment]
Although I think green water is important to consider (because any amount of water use by a plant species is not available anymore). But for the sake of consistency with other crops datasets in ecoinvent, it should probably not be considered.

**Comment by romainsacchi** [comment]
Issue can be re-opened if further discussion is needed.
