### ISSUE TITLE
Error when creating a scenario using Brightway2

### ISSUE THREAD

**Issue by Arezooo33** [polca/premise#138]
I installed Brightway2 and premise 1.8.1
Now, I want to create a scenario using the following code:
from premise import *
import brightway2 as bw

bw.projects.set_current('demo')

ndb = NewDatabase(
      scenarios=[
              {"model":"remind", "pathway":"SSP2-Base", "year":2028}
          ],
      source_db="ev391cutoff", # <-- this is NEW.
      source_version="3.9.1", # <-- this is NEW
      key='XXXXXXXXXXXXXXXXXXXXXXXXX',
      use_multiprocessing=True, # True by default, set to False if multiprocessing is causing troubles
      keep_uncertainty_data=False # False by default, set to True if you want to keep ecoinvent's uncertainty data
  )
Which create a cache file and extract IAM data.
Then I move to update the inventories which gives me an error:
![ndb update error2](https://github.com/polca/premise/assets/153556581/2d2ab1dd-e48a-45c4-b7c5-d9952f51a1ad)
![ndb update error](https://github.com/polca/premise/assets/153556581/c1ba6e55-9e11-4378-8723-0369baf71aa7)
I can't understand what is the problem?

**Comment by Stew-McD** [comment]
I think you can safely remove `nbd.update_two_wheelers`

I looked into this a while ago. As far as I could work out, the files needed to implement the two_wheelers strategies are not fully/correctly in place.  I tried to fix it myself, but I couldn't work it out. 

Unless you are doing an LCA of a motorcycle, I would just remove that line, it shouldn't affect other activities. As far as I know, there is no 'transport by two-wheeler' or similar in ecoinvent.

**Comment by Arezooo33** [comment]
Thanks for your comment, but even when I delete two wheelers I have problem updating steel or DACCS, so I am not sure that the  problem is this.

**Comment by Stew-McD** [comment]
Did you try turning off multiprocessing?

**Comment by Arezooo33** [comment]
Yes and it gives me this error:
![image](https://github.com/polca/premise/assets/153556581/f661bb9f-820b-4b40-b956-1e069e828e83)

**Comment by romainsacchi** [comment]
@Arezooo33 shall I close this issue?
