### ISSUE TITLE
Strange values in scenario diff file

### ISSUE THREAD

**Issue by romainsacchi** [polca/premise#141]
I made a db today with premise 1.8.2.dev2 and found strange values in the scenario diff file.
All production volumes are set at 10 and for all other inputs the amounts are extremely high (not corresponding to a production volume of 10). 
Just noticed that there is a 1.8.2.dev3. Has this already been solved?

**Comment by romainsacchi** [comment]
Can you specify the script you ran (including the scenarios used) so I can reproduce the errors?

**Comment by avdoever** [comment]
```
ndb = NewDatabase(
            scenarios=[
                {"model":"remind", "pathway":"SSP2-PkBudg1150", "year":2020},
                {"model":"remind", "pathway":"SSP2-PkBudg1150", "year":2025},
                {"model":"remind", "pathway":"SSP2-PkBudg1150", "year":2030},
                {"model":"remind", "pathway":"SSP2-PkBudg1150", "year":2035},
                `{"model":"remind","pathway":"SSP2-PkBudg1150", "year":2040},
                {"model":"remind", "pathway":"SSP2-PkBudg1150", "year":2045},
                {"model":"remind", "pathway":"SSP2-PkBudg1150", "year":2050},
            ],
            source_db="ecoinvent 3.8", # <-- name of the database in the BW2 project. Must be a string.
            source_version="3.8", # <-- version of ecoinvent. Can be "3.5", "3.6", "3.7", "3.8", "3.9" or "3.9.1". Must be a string.
            key='blablabla=' # <-- decryption key
            #
    )
ndb.update_all()
ndb.update_cars()
ndb.update_buses()
ndb.write_superstructure_db_to_brightway(name="ei38-SSP2-pkbudg1150-v3")
```

**Comment by romainsacchi** [comment]
@avdoever  I have run these scenarios but do not notice the numbers you mention in the scenario difference file.
Which exchange specifically? Production exchanges? By production volume, you mean the reference output amount of production exchanges in the SDF?

<img width="1472" alt="Screenshot 2024-01-22 at 14 30 03" src="https://github.com/polca/premise/assets/22473067/5b2245bf-3150-44a8-b7d7-c5febc2f6955">

**Comment by avdoever** [comment]
@romainsacchi 
I have checked it again and my system settings for list separators was not compatible with the csv file, which caused an incorrect representation of the numbers. It was the first time the scenario file was exported as csv, so I had not encountered this error before.
