### ISSUE TITLE
Folder `logs` for user-defined inventories is missing

### ISSUE THREAD

**Issue by CHarpprecht** [polca/premise#142]
When importing user-defined scenarios, e.g. via `ndb.update_external_scenario()`, the output states that logging files were created (see output below). However, the `logs` folder does not exist in the stated data folder. 

Output:

```
/////////////////////// EXTRACTING IAM DATA ////////////////////////
Done!

//////////////// IMPORTING USER-DEFINED INVENTORIES ////////////////
Extracted 1 worksheets in 0.02 seconds
Create custom markets.

//////////////// IMPORTING USER-DEFINED INVENTORIES ////////////////
Extracted 1 worksheets in 0.01 seconds
Create custom markets.
Log file of exchanges saved under D:\...\envs\premise\Lib\site-packages\premise\data\logs
Done!
```

Content of the folder D:\...\envs\premise\Lib\site-packages\premise\data:
![image](https://github.com/polca/premise/assets/47253039/b7746ce2-3627-4e76-81d1-253ea1c28c6e)

premise version: 1.8.2.dev3

**Comment by CHarpprecht** [comment]
Could it be that the `logs` folder is not saved in the environment anymore, but in an `export `folder of the respective python project?
I have this `export `folder in my python project:
![image](https://github.com/polca/premise/assets/47253039/d5923b09-03c4-4d31-a93a-f225fa04483d)
and the `logs `folder has the following content, including a file for "external_scenarios":
![image](https://github.com/polca/premise/assets/47253039/bf8f4002-922a-4bc7-985f-3b107b98b21a)

**Comment by romainsacchi** [comment]
The correct filepath is now printed.
The changes occurring during the implementation fo the external scenarios are listed under the "External scenarios" tab in the change report:
<img width="1013" alt="Screenshot 2024-01-30 at 16 37 17" src="https://github.com/polca/premise/assets/22473067/26ed62ee-fcfc-493d-b42a-b802a0b810f2">

However, note that it does not show much at the moment: only the process that have been created or modified.
