### ISSUE TITLE
Suggestion: generate_change_report only provides information of the latest update

### ISSUE THREAD

**Issue by GustavoEzMartinez** [polca/premise#143]
I'm trying to run _ndb.update_steel()_ and _ndb.update_electricity()_ one after the other and generating a change report. However,  the report only shows the latest sector updated. 
I was going through and seems like when running _.update()_ it cleans the cache for all sectors and not only the one to be updated in the logs and therefore the change_report excel file only provides information about the latest sector updated.

**Comment by romainsacchi** [comment]
Hi @GustavoEzMartinez indeed. I do not have a direct solution for this for now.
If I change the access to the log to "add", instead of "write", it will work, but it will also keep the logs from all previous sessions. `update_all()` should show the changes for all sectors though.

**Comment by romainsacchi** [comment]
@GustavoEzMartinez, this should now be fixed in `2.1.0dev5`.
