### ISSUE TITLE
Link with GCAM

### ISSUE THREAD

**Issue by Youyi77** [polca/premise#154]
Hi team,

I am new to the `premise`!

I noticed that in the `iam_variables_mapping` folder, many `.yaml` are already populated with GCAM variables. Seems that it is already linked with GCAM?

So if I want to try to generate user-defined scenarios with GCAM, what I need to do is generate related `.json`, `scenario_data.csv`, `config.yaml`, and `lci-xx.csv` (if needed).

Wondering if I am missing anything.

Greatly appreciate any suggestions!

**Comment by romainsacchi** [comment]
Hi @Youyi77, yes, premise can use GCAM scenarios. We collaborated with NREL to make this happen.
We just have not made them available yet. Once they are, you only need to tell premise which scenario to use (no need for user-defined scenarios). You should write an email to Tapajyoti.Ghosh@nrel.gov to ask when GCAM scenarios will be available.

**Comment by Youyi77** [comment]
Hi @romainsacchi, got it, thanks so much! Looking forward to its release!
