### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Saumyasadhu** [polca/premise#175]
Dear Romain, 
I am using AB with scenario link. However, I'm unable to run the LCA because of this error: 
                          
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sadhu\\AppData\\Local\\pylca\\Brightway3\\Voestalpine-LCA.889fc13890ed2c08af37068074f64c63\\processed\\remind-SSP2-Base-2050.9974b9866154c2f5a8d4f059092fdf53.npy'

Could you tell me what to do about this? 
Thanks!

**Comment by romainsacchi** [comment]
Hello, this is not a `premise` issue. I suggest you file an issue under the `activity-browser` repository.
