### ISSUE TITLE
updating to premise 2.1.1 

### ISSUE THREAD

**Issue by Lmachinferrero** [polca/premise#176]
Hello!! 
When updating (to work with ecoinvent 3.10), the premise version 2.1.0 still continues... How should I do to have premise 2.1.1?

Of course, when trying to modify the inventories the following error appears:
"Only ['3.5', '3.6', '3.7', '3.7.1', '3.8', '3.9', '3.9.1'] are currently supported, not 3.10."

Thank you!!

**Comment by romainsacchi** [comment]
Hi @Lmachinferrero ,

you can try `pip install premise==2.1.1.dev8`

**Comment by romainsacchi** [comment]
Or `conda install romainsacchi::premise`

**Comment by Lmachinferrero** [comment]
Thank you very much Romain.
It was installed perfectly, but when trying to transform Ecoinvent 3.10 the following error appears:

![error](https://github.com/user-attachments/assets/3ffbe399-ab7e-4218-8468-5778683a362b)

**Comment by romainsacchi** [comment]
Hi @Lmachinferrero 
indeed, I forgot to package some files.
As a short fix, you can copy [these three files](https://github.com/polca/premise/tree/master/premise/data/battery) in `premise/data/battery` in `premise` root folder on your computer.

**Comment by Lmachinferrero** [comment]
I did it and it worked successfully!! 
Thanks a lot Romain.
