### ISSUE TITLE
AttributeError: 'ProjectManager' object has no attribute 'migrate_project_25'

### ISSUE THREAD

**Issue by MMahdi97** [polca/premise#177]
Hello everyone,

I am trying to use the Activity Browser for a simple model but when I want to calculate the impact I will have this error:
` bw2data.errors.Brightway2Project: Please use `projects.migrate_project_25` before calculating using Brightway 2.5`

According to the explanation here: https://github.com/brightway-lca/brightway25 , I understand I need to use this function `bw2data.projects.migrate_project_25()`, but I don't know where should I write this code!?
I tried to use this code in my main code in Premise, but I get this error:
![image](https://github.com/user-attachments/assets/0e8eee6f-6efc-4916-9759-821cd99d9597)

Could someone please help me with this problem?

**Comment by romainsacchi** [comment]
Hi @MMahdi97, this should be an issue for the `bw2data` GitHub repository.
I suspect you have BW 2.5 in your environment. However, the databases in your active projects were created using BW 2. So, it's telling you to convert those databases if you want to open them using BW 2.5. However, note that this process is not reversible. Also, note that Activity Browser is not yet compatible with BW 2.5.
