### ISSUE TITLE
type hinting of key

### ISSUE THREAD

**Issue by marc-vdm** [polca/premise#179]
I was just copying an example in pycharm (e.g. https://github.com/polca/premise/blob/master/examples/examples.ipynb)

It seems that `key` for `NewDatabase()` is expected as `bytes` but is (always?) given as `str`

https://github.com/polca/premise/blob/1a1f9bdc46db1025e475077810cb1d1b7fde1a83/premise/new_database.py#L505

Perhaps consider updating the type hinting to `str` or `Union[bytes, str]`?

**Comment by romainsacchi** [comment]
Fixed in https://github.com/polca/premise/commit/a097eed69dba3373a90319e7149a0cab3b970f83
