### ISSUE TITLE
Use of external scenarios fails if exchange amount is 0 and exchange has uncertainty

### ISSUE THREAD

**Issue by marc-vdm** [polca/premise#180]
The below will divide by zero if `exc["amount"] == 0`

https://github.com/polca/premise/blob/1a1f9bdc46db1025e475077810cb1d1b7fde1a83/premise/external.py#L1496-L1506

To replicate: 

Follow [this example](https://github.com/premise-community-scenarios/ammonia-prospective-scenarios?tab=readme-ov-file#how-to-use-it) ~~(though also apply fix for scenario names)~~

edit: FYI, you can replace the `if` with `if ("minimum" in exc and exc["amount"] != 0)`, which I did as a temporary fix, but I do not know what that does with the actual uncertainties where `exc["amount"] == 0`.

**Comment by romainsacchi** [comment]
Fixed in https://github.com/polca/premise/commit/94b3908f1f5aa1dfb2d2618f07f0a9832e6913f3
