### ISSUE TITLE
external scenario LCI name capitalization

### ISSUE THREAD

**Issue by marc-vdm** [polca/premise#182]
I am creating external scenarios and ran into the following problem:

In my LCI, I have an activity with the name `Advanced Dry Recovery (ADR)` and an activity with the name `ADR`. These activities have variables attached in my configuration, where I refer to these names to match them.

I found that the `ADR` activity matched without issue, but the `Advanced Dry Recovery (ADR)` would not. After inspection, it turns out that the second process is written to Brightway as `advanced Dry Recovery (ADR)` (note the lower case first letter). After changing my LCI and config file to `advanced Dry Recovery (ADR)`, Premise matched the correct variable without issue.

Somehow Premise is lower-casing the first letter (but only in some cases??), which cause Premise to fail to link.

**Comment by romainsacchi** [comment]
[There's a function](https://github.com/polca/premise/blob/ba2e9f81ef5be491ea730ad30d2a6d9683b4a7d6/premise/inventory_imports.py#L731) that indeed lower-caps names and reference products of datasets and exchanges, except if it starts with an acronym. This is to align more with the ecoinvent naming convention.

I think https://github.com/polca/premise/commit/399923109553eb3940d775041adca9262d5917a3 fixes the issue. Can you try it?
