### ISSUE TITLE
external scenario superstructure export problem

### ISSUE THREAD

**Issue by marc-vdm** [polca/premise#183]
When I create custom inventories in an external scenario and export them as normal brightway scenarios, they work without issue. 

Activities can be set to produce some other amount than 1 of their product. This is registered properly in normal Brightway exports.

However, when I export as superstructure, the production amount in the process and SDF file are set to 1 (maybe also -1 where relevant, I haven't tried with negative flows).

I'm sure this is not supposed to happen.

edit: temporary solve for now is to manually scale all inventories to produce 1 unit

**Comment by romainsacchi** [comment]
OK, I will look into it.

**Comment by romainsacchi** [comment]
https://github.com/polca/premise/commit/0cf3a5ed5a79125def4a1cc09e33ad688c52ec16 should fix this. Re-open if not.
