### ISSUE TITLE
Cement update not linking properly with regional markets for clinker?

### ISSUE THREAD

**Issue by kebamba** [polca/premise#184]
When I create a new database  and I only update the cement industry, there are some cement production typew for which the clinker is not linked to the regional clinker market but to clinker production. Thus, it is not taking into account the adoption of CCS in the clinker production for this regions. Example ("model": "image", "pathway": "SSP2-RCP26", "year": 2050. From Ecoinvent v3.9.1 cutoff):
39.8% of 'cement production, Portland (RoW)' comes from 'cement production, Portland (INDIA)'. However, the clinker input for 'cement production, Portland (INDIA)' is 'clinker production (INDIA)', instead of 'market for clinker production (INDIA)'. This is very influential in the climate change results, as 'clinker production (INDIA)' emits ~1.02 kgCO2/kg cement, while 'market for clinker (INDIA) emits ~0.65 kgCO2/kg cement. 

The same happens for other regional markets. Also when trying other IMAGE pathways. Am I overlooking something?

**Comment by romainsacchi** [comment]
Hi @kebamba,
I understand the issue. That is because some cement production datasets in the original ecoinvent database use the clinker production dataset directly, not the market. I'll fix this and will let you know.

**Comment by romainsacchi** [comment]
https://github.com/polca/premise/commit/72f656ec00c18147d16a611d6a375e5a40b3bf78 fixes the issue. You can pip install directly from the repo to try it out or wait for the next 1.2.4 release (maybe later today). Re-open the issue is not solved.
