### ISSUE TITLE
Electricity input in hydrogen production electrolyzers not properly adapted?

### ISSUE THREAD

**Issue by kebamba** [polca/premise#185]
The original datasets for hydrogen production for PEM (hydrogen production, gaseous, 30 bar, from PEM electrolysis, from grid electricity), AEC (hydrogen production, gaseous, 20 bar, from AEC electrolysis, from grid electricity) and SOEC (hydrogen production, gaseous, 1 bar, from SOEC electrolysis, from grid electricity) have an electricity input of 54 kWh, 51.8 kWh and 42.3 kWh, respectively. However, after calling ndb.update('biofuels') to an IMAGE, SSP2-RCP26, 2050 scenario, these amounts are drastically increased, as the new regional 'market for electricity' inputs seem to be misscalculated.
Example: 
'hydrogen production, gaseous, 1 bar, from SOEC electrolysis, from grid electricity' (WEU) has now 20 electricity inputs, all of them of 40.6 kWh each. Thus, now the electricity input of the activity is 812 kWh instead of the original 42.3 kWh in the imported dataset.
Something similar happens with AEC and PEM electrolysis activities. 

Sorry if I am missing something!

**Comment by romainsacchi** [comment]
You mean `.update("fuels")` right?

**Comment by romainsacchi** [comment]
Which version do you use?

**Comment by kebamba** [comment]
Yes, I meant .update('fuels'). Sorry about that. It is premise v2.1.3

**Comment by romainsacchi** [comment]
https://github.com/polca/premise/commit/5881ff9317d19d3ade83be066ca288c32389e16f fixes the issue. You can pip install directly from the repo to try it out or wait for the next `1.2.4` release (maybe later today). Re-open the issue is not solved.
