### ISSUE TITLE
ValueError: Fix the unlinked exchanges before proceeding

### ISSUE THREAD

**Issue by OliverLyon** [polca/premise#186]
I tried to use the NewDatabase function to initialize the new database and it want me to fix the unlinked changes. Does anyone know how to solve this? Here is the output error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[12], line 10
      7 bd.projects.set_current("bw25_project_test")
      9 # Initialize the NewDatabase object with scenario settings
---> 10 ndb = NewDatabase(
     11     scenarios=[
     12         {"model": "remind", "pathway": "SSP2-Base", "year": 2028}
     13     ],
     14     source_version="3.7.1",
     15     source_db="ecoinvent_3.7.1_cutoff_ecoSpold02"
     16 )
     18 # Import the ecoinvent database from the specified path (for ecospold2 datasets)
     19 ndb.import_ecoinvent(
     20     source_file_path=r"C:\Users\Desktop\EcoInvent\ecoinvent 3.7.1_cutoff_ecoSpold02\datasets",
     21     source_type="ecospold"
     22 )

File [~\.conda\envs\brightway25\Lib\site-packages\premise\new_database.py:604](http://localhost:8888/lab/tree/Desktop/Jupyter-notebook/~/.conda/envs/brightway25/Lib/site-packages/premise/new_database.py#line=603), in NewDatabase.__init__(self, scenarios, source_version, source_type, key, source_db, source_file_path, additional_inventories, system_model, system_args, use_cached_inventories, use_cached_database, external_scenarios, quiet, keep_imports_uncertainty, keep_source_db_uncertainty, gains_scenario, use_absolute_efficiency, biosphere_name)
    602 print("- Extracting inventories")
    603 if use_cached_inventories:
--> 604     data = self.__find_cached_inventories(source_db)
    605     if data is not None:
    606         self.database.extend(data)

File [~\.conda\envs\brightway25\Lib\site-packages\premise\new_database.py:686](http://localhost:8888/lab/tree/Desktop/Jupyter-notebook/~/.conda/envs/brightway25/Lib/site-packages/premise/new_database.py#line=685), in NewDatabase.__find_cached_inventories(self, db_name)
    684 # else, extract the database, pickle it for next time and return it
    685 print("Cannot find cached inventories. Will create them now for next time...")
--> 686 data = self.__import_inventories()
    687 pickle.dump(data, open(file_name, "wb"))
    688 print(
    689     "Data cached. It is advised to restart your workflow at this point[.\n](http://localhost:8888/lab/tree/Desktop/Jupyter-notebook/n)"
    690     "This allows premise to use the cached data instead, which results in\n"
    691     "a faster workflow."
    692 )

File [~\.conda\envs\brightway25\Lib\site-packages\premise\new_database.py:823](http://localhost:8888/lab/tree/Desktop/Jupyter-notebook/~/.conda/envs/brightway25/Lib/site-packages/premise/new_database.py#line=822), in NewDatabase.__import_inventories(self)
    820     unlinked.extend(inventory.list_unlinked)
    822 if len(unlinked) > 0:
--> 823     raise ValueError("Fix the unlinked exchanges before proceeding")
    825 return data

ValueError: Fix the unlinked exchanges before proceeding

**Comment by romainsacchi** [comment]
In less than an hour, `v.2.1.9` will be released (`pip install premise==2.1.9`). This should fix the linking issues. Re-open this issue if it is not the case.

**Comment by OliverLyon** [comment]
I tried to use pip install premise==2.1.9 and received the following error. Is it related to the environment I created? (I tried to install in both python 3.10 and 3.11).

(premise) c:\users\zhiliang>pip install premise==2.1.9
ERROR: Ignored the following versions that require a different python version: 1.5.1 Requires-Python >=3.9,<3.11; 1.5.2 Requires-Python >=3.9,<3.11; 1.5.3 Requires-Python >=3.9,<3.11; 1.5.4 Requires-Python >=3.9,<3.11; 1.5.5 Requires-Python >=3.9,<3.11; 1.5.6 Requires-Python >=3.9,<3.11; 1.5.7 Requires-Python >=3.9,<3.11; 1.5.8 Requires-Python >=3.9,<3.11; 1.5.9 Requires-Python >=3.9,<3.11; 1.6.0 Requires-Python >=3.9,<3.11; 1.6.1 Requires-Python >=3.9,<3.11; 1.6.2 Requires-Python >=3.9,<3.11; 1.6.3 Requires-Python >=3.9,<3.11; 1.6.4 Requires-Python >=3.9,<3.11; 1.6.5 Requires-Python >=3.9,<3.11; 1.6.6 Requires-Python >=3.9,<3.11; 1.6.7 Requires-Python >=3.9,<3.11; 1.6.8 Requires-Python >=3.9,<3.11; 1.6.9 Requires-Python >=3.9,<3.11; 1.7.0 Requires-Python >=3.9,<3.11; 1.7.1 Requires-Python >=3.9,<3.11; 1.7.2 Requires-Python >=3.9,<3.11; 1.7.3 Requires-Python >=3.9,<3.11; 1.7.4 Requires-Python >=3.9,<3.11; 1.7.5 Requires-Python >=3.9,<3.11; 1.7.6 Requires-Python >=3.9,<3.11; 1.7.8 Requires-Python >=3.9,<3.11; 1.7.9 Requires-Python >=3.9,<3.11
ERROR: Could not find a version that satisfies the requirement premise==2.1.9 (from versions: 1.8.0, 1.8.1, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1.dev0, 2.1.1.dev1, 2.1.1.dev2, 2.1.1.dev3, 2.1.1.dev4, 2.1.1.dev5, 2.1.1.dev6, 2.1.1.dev8, 2.1.1.dev9, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5)
ERROR: No matching distribution found for premise==2.1.9

**Comment by romainsacchi** [comment]
Indeed, a test in the CI pipeline failed, and `2.1.9` has not been released. I will get back to you.

**Comment by romainsacchi** [comment]
OK, `2.1.9` is finally released. Re-open the issue if that does not fix it.
