### ISSUE TITLE
Premise in SimaPro

### ISSUE THREAD

**Issue by MaximeAgez** [polca/premise#188]
Hi,
I've been using the v2.2 of premise to use remind with ecoinvent3.10 and the plan is to export to SimaPro. Whenever I get to the write_db_to_simapro function the kernal of my jupyter lab always dies (like 4 times in a row after restarting). Since it's recurring I assume it might have something to do with the function itself? Note that the csv file is produced, but I'm not sure if it's the final version logs and stuff are not. So the issue erupts in the middle I guess.

On another note, whenever I import the csv file into a SimaPro database where ecoinvent is already there, the software says that processes of ecoinvent won't be updated. So it seems that electricity and such are not updated and only the additional processes of premise are written. Is that the intended way? Am I supposed to import premise on a new empty database in SimaPro for it to have updated processes?

Thanks!

**Comment by romainsacchi** [comment]
Hi @MaximeAgez 
Regarding the import into Simapro, you need to create a project, import the CSV, and then turn the project into a library that you activate from other projects.

**Comment by romainsacchi** [comment]
Regarding the first issue, I'm not sure. It works well on my end, and this issue has not been reported before.
It could be a RAM issue. Maybe try to monitor your RAM usage and see if it is the problem, and possibly shut other non-necessary applications to free up some memory.

**Comment by romainsacchi** [comment]
Should I close this issue?

**Comment by MaximeAgez** [comment]
Yes the issue can be closed. The import as library worked. However, the kernel dying still happens, and I don't think it's a problem of RAM because it never went to 100% usage at all.
