### ISSUE TITLE
support of 3.7.1 (and semantic versionning tags of ecoinvent 3)

### ISSUE THREAD

**Issue by tngTUDOR** [polca/premise#24]
#16 hit back: ecoinvent version 3.7.1 is out and this cannot be coerced to a "float".

## Current
The NewDatabase validates the version of Ecoinvent as a "float", but the latest version (of ecoinvent) is a semantic versionning tag: "3.7.1"

AT this point, I think this is more of a "discussion" rather than a formal request for change in the code: Is premise supposed to support "generic" major versions of ecoinvent 3.7, 3.6 and so on ?
ON the other hand, ecoinvent release "3.7.1" and as usual, it tells that we should prefer 3.7.1 over 3.7 !

What do you think ? @romainsacchi

**Comment by romainsacchi** [comment]
@tngTUDOR  Indeed, it makes a lot of sense. This will be done, as well as other things, in the next push (maybe today, probably tomorrow).

**Comment by romainsacchi** [comment]
So, as of 0.2.0, the following should work:

ndb = NewDatabase(
            scenarios=[
                {"model":"remind", "pathway":"SSP2-Base", "year":2030,},
                {"model":"image", "pathway":"SSP2-Base", "year":2030,},
            ],
            source_db="ecoinvent 3.7 cutoff",
            source_version="3.7" <-- or "3.5", "3.6", "3.7.1"
    )
