### ISSUE TITLE
EncodingError

### ISSUE THREAD

**Issue by marcosdbw** [polca/premise#29]
Hi, I started using premise codes using jupyter lab, and at the moment I am trying to create a NewDatabase by extracting a 3.6 ecoinvent database in ecospold format. However, the following error appears when Importing Default inventories:

MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7fedc3aafbe0>'. Reason: 'TypeError("cannot pickle 'lxml.etree._ListErrorLog' object")'. Do you know how this problem could be solved? Thanks a lot.

--------------------------------------------------------------------------
MaybeEncodingError                        Traceback (most recent call last)
<ipython-input-5-4dc27a50a6a5> in <module>
----> 1 ndb = NewDatabase(
      2         scenarios = [
      3             {"model":"remind", "pathway":"SSP2-NDC", "year":2030}
      4         ],        
      5         source_type="ecospold",

~/.conda/envs/my3.9env/lib/python3.9/site-packages/premise/ecoinvent_modification.py in __init__(self, scenarios, source_version, source_type, key, source_db, source_file_path, additional_inventories, direct_import)
    467             "\n////////////////////// EXTRACTING SOURCE DATABASE ///////////////////////"
    468         )
--> 469         self.db = self.clean_database()
    470         print(
    471             "\n/////////////////// IMPORTING DEFAULT INVENTORIES ////////////////////"

~/.conda/envs/my3.9env/lib/python3.9/site-packages/premise/ecoinvent_modification.py in clean_database(self)
    489         :return:
    490         """
--> 491         return DatabaseCleaner(
    492             self.source, self.source_type, self.source_file_path
    493         ).prepare_datasets()

~/.conda/envs/my3.9env/lib/python3.9/site-packages/premise/clean_datasets.py in __init__(self, source_db, source_type, source_file_path)
     36         if source_type == 'ecospold':
     37             # The ecospold data needs to be formatted
---> 38             ei = bw2io.SingleOutputEcospold2Importer(source_file_path, source_db)
     39             ei.apply_strategies()
     40             self.db = ei.data

~/.conda/envs/my3.9env/lib/python3.9/site-packages/bw2io/importers/ecospold2.py in __init__(self, dirpath, db_name, extractor, use_mp, signal)
     69         start = time()
     70         try:
---> 71             self.data = extractor.extract(dirpath, db_name, use_mp=use_mp)
     72         except RuntimeError as e:
     73             raise MultiprocessingError(

~/.conda/envs/my3.9env/lib/python3.9/site-packages/bw2io/extractors/ecospold2.py in extract(cls, dirpath, db_name, use_mp)
     85                     for x in filelist
     86                 ]
---> 87                 data = [p.get() for p in results]
     88         else:
     89             pbar = pyprind.ProgBar(

~/.conda/envs/my3.9env/lib/python3.9/site-packages/bw2io/extractors/ecospold2.py in <listcomp>(.0)
     85                     for x in filelist
     86                 ]
---> 87                 data = [p.get() for p in results]
     88         else:
     89             pbar = pyprind.ProgBar(

~/.conda/envs/my3.9env/lib/python3.9/multiprocessing/pool.py in get(self, timeout)
    769             return self._value
    770         else:
--> 771             raise self._value
    772 
    773     def _set(self, i, obj):

MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7fedc3aafbe0>'. Reason: 'TypeError("cannot pickle 'lxml.etree._ListErrorLog' object")'

**Comment by romainsacchi** [comment]
Hi, I'm afraid I cannot help much.

I just tried it:

ndb = NewDatabase(
             scenarios=[
                 {"model":"remind", "pathway":"SSP2-NDC", "year":2030}
            ],
            source_type="ecospold",
            source_file_path=r"C:\Users\sacchi_r\Dropbox\ecoinvent 3.7.1_cutoff_ecoSpold02\datasets",
            source_version="3.7.1", 
            key='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
)

And I did not encounter any issue. Although, it was with ecoinvent 3.7.1.
Did you specify `source_file_path`? I know that one has to add "r" just in front, so that the back-slash is not considered an escape character but as a raw string.

By the way, I just added a small fix today (unrelated to your issue though), hence, make sure to use 0.4.0.

**Comment by Loisel** [comment]
Which python version do you use? I encountered errors with pickle in
versions below python 3.9.

Best, Alois

Am 28.05.21 um 16:01 schrieb romainsacchi:

**Comment by marcosdbw** [comment]
Thanks, Romain, for your help.
Yes, I specified the file path, including the r just in front.
I will keep trying to run it. On my laptop I had no issues, but the code
did not run because it was out of memory after a couple of hours running.
This issue appeared when trying to run it on the server, which has a python
3.8.5. I created a python 3.9 environment to run premise, but this issue
appeared.

But thanks, anyway:)

Em sex, 28 de mai de 2021 16:01, romainsacchi ***@***.***>
escreveu:

**Comment by marcosdbw** [comment]
Hi Alois, I am running it using a python 3.9 environment (which I had to
create since i have access to a python 3.8.5 server).

Em sex, 28 de mai de 2021 20:57, Loisel ***@***.***> escreveu:

**Comment by romainsacchi** [comment]
OK. Can you check the version of bw2io being used?
We did not set a version requirement for bw2io, but we should have. It should be at least 0.8.2.

**Comment by marcosdbw** [comment]
I have just checked bw2io, it is the 0.8.3.1 version.

Em sáb., 29 de mai. de 2021 às 19:31, romainsacchi ***@***.***>
escreveu:

**Comment by romainsacchi** [comment]
I just tried with bw2io 0.8.3 without an issue. So it's not that.

**Comment by romainsacchi** [comment]
Hi @cmutel , do you have an idea about this?

**Comment by marcosdbw** [comment]
Hi @romainsacchi @Loisel . I have just made a double-check on my dataset and found out that the encoding issue was occurring because of my ecoinvent dataset which somehow had some files missing. I extracted the ecospold database again to my PC and premise codes are working fine. Thanks for your help.

**Comment by romainsacchi** [comment]
You're welcome. Good to hear!

**Comment by cmutel** [comment]
I also couldn't reproduce this - my guess is that not only did you have some files missing (this wouldn't raise an error, they just wouldn't be there), but you also had one or more files which were not completely decompressed, which meant the XML parser couldn't read them, and that is what the `lxml.etree._ListErrorLog` was about.

Not sure why that object wouldn't be able to be pickled. I would accept a PR to catch parsing errors in bw2io, but am not going to invest the time myself on a very rare error.
