### ISSUE TITLE
InvalidLink: Exchange links to non-existent activity

### ISSUE THREAD

**Issue by marcosdbw** [polca/premise#31]
Hi all,
I am running premise using an ecoinvent 3.6 ecospold database. Everything is working fine when creating new databases using REMIND SSP2_NDC scenario for many different years and then writing them to Brightway2 format. However, when using REMIND SSP2_Base, NPi, and PkBudg scenario, an error appears when writing the new database to Brightway2. It is something related to exchange links to a non-existent activity. In case you have any idea how to solve this, I would appreciate it a lot. Thanks again. 

....
Relink new steel production datasets to steel-consuming activities
Write new database(s) to Brightway2.
One or multiple duplicates detected. Removing them...
---------------------------------------------------------------------------
InvalidLink                               Traceback (most recent call last)
<ipython-input-30-25afe7de94e4> in <module>
     12 
     13 ndb.update_all()
---> 14 ndb.write_db_to_brightway()

~\Anaconda3\envs\myenv\lib\site-packages\premise\ecoinvent_modification.py in write_db_to_brightway(self, name)
    843             scenario["database"] = self.check_for_duplicates(scenario["database"])
    844 
--> 845             wurst.write_brightway2_database(
    846                 scenario["database"], name[s],
    847             )

~\Anaconda3\envs\myenv\lib\site-packages\wurst\brightway\write_database.py in write_brightway2_database(data, name)
     49     change_db_name(data, name)
     50     link_internal(data)
---> 51     check_internal_linking(data)
     52     check_duplicate_codes(data)
     53     WurstImporter(name, data).write_database()

~\Anaconda3\envs\myenv\lib\site-packages\wurst\linking.py in check_internal_linking(data)
     42             if exc.get("input") and exc["input"][0] in names:
     43                 if exc["input"] not in keys:
---> 44                     raise InvalidLink(
     45                         "Exchange links to non-existent activity:\n{}".format(
     46                             pformat(exc)

InvalidLink: Exchange links to non-existent activity:
{'activity': 'e7fbcb70-eb35-4d42-8905-a18441378a0e',
 'amount': 1.0,
 'classifications': {'CPC': ['37430: Cement clinkers']},
 'comment': 'EcoSpold01Location=CH',
 'flow': '1f41586d-0d8a-4c7c-8473-dd8351bab538',
 'input': ('ecoinvent_remind_SSP2-NPi_2043',
           '5b97c4e3c5775588a48fa1233e6d8d22'),
 'loc': 1.0,
 'location': 'LAM',
 'name': 'clinker production',
 'product': 'clinker',
 'production volume': 42822334344.0,
 'properties': {'carbon allocation': {'amount': 0.0,
                                      'comment': 'carbon content per unit of '
                                                 'product (reserved; not for '
                                                 'manual entry)',
                                      'unit': 'kg'},
                'carbon content': {'amount': 0.0,
                                   'comment': 'carbon content on a dry matter '
                                              'basis (reserved; not for manual '
                                              'entry)',
                                   'unit': 'dimensionless'},
                'carbon content, fossil': {'amount': 0.0,
                                           'comment': 'Tab 3.2, part II '
                                                      'ecoinvent v2.2 report 7',
                                           'unit': 'dimensionless'},
                'carbon content, non-fossil': {'amount': 0.0,
                                               'comment': 'Tab 3.2, part II '
                                                          'ecoinvent v2.2 '
                                                          'report 7',
                                               'unit': 'dimensionless'},
                'dry mass': {'amount': 1.0, 'unit': 'kg'},
                'price': {'amount': 0.047,
                          'comment': 'Calculated value based on data from '
                                     'United Nations Commodity Trade '
                                     'Statistics Database (comtrade.un.org). '
                                     'UN comtrade category: 252310 Cement '
                                     'Clinkers. Using exchange rate of 1EURO = '
                                     '1.209 USD. Average of price of import '
                                     'into 5 main markets (EU, US, JP, IN and '
                                     'CN).',
                          'unit': 'EUR2005'},
                'water content': {'amount': 0.0,
                                  'comment': 'water mass/dry mass',
                                  'unit': 'dimensionless'},
                'water in wet mass': {'amount': 0.0, 'unit': 'kg'},
                'wet mass': {'amount': 1.0, 'unit': 'kg'}},
 'type': 'production',
 'uncertainty type': 0,
 'unit': 'kilogram'}

**Comment by romainsacchi** [comment]
Hi @marcosdbw ,

sorry about this. May I have the exact lines that you ran to produce this error?

**Comment by marcosdbw** [comment]
Hi @romainsacchi, thanks for your reply. Sure. Please see below the exact lines that I ran (I deleted the encryption key). Everything runs fine, all update/transformation functions work fine, but the error appears at the end when writing the new database do BW format.

ndb = NewDatabase(
        scenarios = [
            {"model":"remind", "pathway":"SSP2-PkBudg1300", "year":2030}
        ],        
        source_type="ecospold", 
        source_file_path=r"C:\datasetecospold02\ecoinvent3.6_cut-off_ecoSpold02\datasets", 
        source_version="3.6",
	key='XXXXXXXXXXXXXXXXXXXXXXXXXXX' 
    )

ndb.update_all()
ndb.write_db_to_brightway()

**Comment by romainsacchi** [comment]
Hi @marcosdbw ,

the latest version on anaconda cloud should fix your issue.
Let me know.

**Comment by marcosdbw** [comment]
Hi @romainsacchi,
Great. I have just tested the latest version and is working perfectly.
Thanks very much.
