### ISSUE TITLE
Add GWP of hydrogen to impact category

### ISSUE THREAD

**Issue by CHarpprecht** [polca/premise#53]
Add GWP of hydrogen to air to impact category of climate change to account for H2 leakages in a hydrogen economny

GWP: 5.8 kg CO2-eq / kg H2
according to Derwent et al. 2006

Derwent, R.G., Simmonds, P.G., O'Doherty, S.J., Manning, A.J., Collins, W.J., & Stevenson, D.S. (2006). Global environmental impacts of the hydrogen economy. International Journal of Nuclear Hydrogen Production and Applications, 1, 57-67.

IPCC also uses 5.8 https://archive.ipcc.ch/publications_and_data/ar4/wg1/en/ch2s2-10-3-6.html

**Comment by romainsacchi** [comment]
Done. The library `premise_gwp` [here](https://github.com/romainsacchi/premise_gwp) does just that now, based on a more recent study of [Derwent et al](https://www.sciencedirect.com/science/article/pii/S0360319920302779). The library also installs a version of the IPCC method, with -1/+1 CFs for biogenic CO2.
