### ISSUE TITLE
Update_electricity()  does not work for remind scenarios

### ISSUE THREAD

**Issue by CHarpprecht** [polca/premise#59]
Update_electricity()  does not work for remind scenarios (I imported only 1 remind scenario). It produces the following error:

+------------------------------------------------------------------+
| Warning                                                          |
+------------------------------------------------------------------+
| Because some of the scenarios can yield LCI databases            |
| containing net negative emission technologies (NET),             |
| it is advised to account for biogenic CO2 flows when calculating |
| Global Warming potential indicators.                             |
| `premise_gwp` provides characterization factors for such flows.  |
|                                                                  |
| Install it via                                                   |
| pip install premise_gwp                                          |
| or                                                               |
| conda install -c romainsacchi premise_gwp                        |
|                                                                  |
| Within your bw2 project:                                         |
| from premise_gwp import add_premise_gwp                          |
| add_premise_gwp()                                                |
+------------------------------------------------------------------+

////////////////////// EXTRACTING SOURCE DATABASE //////////////////
Done!

/////////////////// IMPORTING DEFAULT INVENTORIES //////////////////
Done!

////////////////////// EXTRACTING IAM DATA /////////////////////////
Done!

/////////////////// ELECTRICITY ////////////////////
More than one region found for GR:['EUR', 'ESC']
More than one region found for RO:['EUR', 'ECS']
More than one region found for CH:['NEU', 'NEN']
More than one region found for BE:['EUR', 'EWN']
More than one region found for DE:['EUR', 'DEU']
More than one region found for HU:['EUR', 'ECS']
More than one region found for SE:['EUR', 'ENC']
More than one region found for CY:['EUR', 'ESC']
More than one region found for AT:['EUR', 'EWN']
More than one region found for DK:['EUR', 'ENC']
More than one region found for PT:['EUR', 'ESW']
More than one region found for LT:['EUR', 'ECE']
More than one region found for FR:['EUR', 'FRA']
More than one region found for IT:['EUR', 'ESC']
More than one region found for NL:['EUR', 'EWN']
More than one region found for HR:['EUR', 'ECS']
More than one region found for ES:['EUR', 'ESW']
More than one region found for SK:['EUR', 'ECE']
More than one region found for MK:['NEU', 'NES']
More than one region found for CZ:['EUR', 'ECE']
More than one region found for NO:['NEU', 'NEN']
More than one region found for PL:['EUR', 'ECE']
More than one region found for RS:['NEU', 'NES']
More than one region found for GB:['EUR', 'UKI']
More than one region found for IS:['NEU', 'NEN']
More than one region found for BA:['NEU', 'NES']
More than one region found for BG:['EUR', 'ECS']
More than one region found for IE:['EUR', 'UKI']
More than one region found for MT:['EUR', 'ESC']
More than one region found for XK:['EUR', 'NES']
More than one region found for FI:['EUR', 'ENC']
More than one region found for LU:['EUR', 'EWN']
More than one region found for EE:['EUR', 'ECE']
More than one region found for SI:['EUR', 'ECS']
More than one region found for TR:['MEA', 'NES']
More than one region found for AL:['NEU', 'NES']
More than one region found for LV:['EUR', 'ECE']
More than one region found for ME:['NEU', 'NES']
More than one region found for GI:['EUR', 'UKI']
Adjust efficiency of power plants...
Log of changes in power plants efficiencies saved in 
Rescale inventories and emissions for Biomass CHP

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\.conda\envs\premiseenv\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3360             try:
-> 3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:

~\.conda\envs\premiseenv\lib\site-packages\pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

~\.conda\envs\premiseenv\lib\site-packages\pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: None

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_17096/2751985968.py in <module>
     16     )
     17 
---> 18 ndb.update_electricity()
     19 
     20 #ndb.write_db_to_brightway(name="test_elec3")

c:\users\harp_ca\pycharmprojects\premise\premise\premise\ecoinvent_modification.py in update_electricity(self)
    848         )
    849         # scenario["database"] = electricity.update_electricity_markets()
--> 850         self.database = electricity.update_electricity_efficiency()
    851 
    852     def update_fuels(self):

c:\users\harp_ca\pycharmprojects\premise\premise\premise\electricity.py in update_electricity_efficiency(self)
   1091 
   1092                             # Find relative efficiency change indicated by the IAM
-> 1093                             scaling_factor = 1 / dict_technology["IAM_eff_func"](
   1094                                 variable=technology,
   1095                                 location=loc,

c:\users\harp_ca\pycharmprojects\premise\premise\premise\transformation.py in find_iam_efficiency_change(self, variable, location, year, scenario)
    466         """
    467 
--> 468         scaling_factor = self.iam_data.efficiency.sel(
    469             region=location, variables=variable, year=int(year), scenario=scenario
    470         ).values.item(0)

~\.conda\envs\premiseenv\lib\site-packages\xarray\core\dataarray.py in sel(self, indexers, method, tolerance, drop, **indexers_kwargs)
   1252         Dimensions without coordinates: points
   1253         """
-> 1254         ds = self._to_temp_dataset().sel(
   1255             indexers=indexers,
   1256             drop=drop,

~\.conda\envs\premiseenv\lib\site-packages\xarray\core\dataset.py in sel(self, indexers, method, tolerance, drop, **indexers_kwargs)
   2228         """
   2229         indexers = either_dict_or_kwargs(indexers, indexers_kwargs, "sel")
-> 2230         pos_indexers, new_indexes = remap_label_indexers(
   2231             self, indexers=indexers, method=method, tolerance=tolerance
   2232         )

~\.conda\envs\premiseenv\lib\site-packages\xarray\core\coordinates.py in remap_label_indexers(obj, indexers, method, tolerance, **indexers_kwargs)
    414     }
    415 
--> 416     pos_indexers, new_indexes = indexing.remap_label_indexers(
    417         obj, v_indexers, method=method, tolerance=tolerance
    418     )

~\.conda\envs\premiseenv\lib\site-packages\xarray\core\indexing.py in remap_label_indexers(data_obj, indexers, method, tolerance)
    268             coords_dtype = data_obj.coords[dim].dtype
    269             label = maybe_cast_to_coords_dtype(label, coords_dtype)
--> 270             idxr, new_idx = convert_label_indexer(index, label, dim, method, tolerance)
    271             pos_indexers[dim] = idxr
    272             if new_idx is not None:

~\.conda\envs\premiseenv\lib\site-packages\xarray\core\indexing.py in convert_label_indexer(index, label, index_name, method, tolerance)
    189                 indexer = index.get_loc(label_value)
    190             else:
--> 191                 indexer = index.get_loc(label_value, method=method, tolerance=tolerance)
    192         elif label.dtype.kind == "b":
    193             indexer = label

~\.conda\envs\premiseenv\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:
-> 3363                 raise KeyError(key) from err
   3364 
   3365         if is_scalar(key) and isna(key) and not self.hasnans:

KeyError: None

**Comment by romainsacchi** [comment]
This works on my end.
Can you check the version of `wurst` you use?
It should be pinned to `0.3.0`.

**Comment by CHarpprecht** [comment]
I have version 0.3.1, should it be downgraded to 0.3.0?

**Comment by romainsacchi** [comment]
Yes. I have specified it in the requirement file, hence I'm wondering how it is you have 0.3.1.
`wurst 0.3.1` is meant to work with the new REMIND files (with additional European sub-regions), ... which we do not yet have.

**Comment by CHarpprecht** [comment]
Thank you, setting wurst to version 0.3.0 resolved the problem :)
