### ISSUE TITLE
0.4 (and potentially 1.0) versions are not compatible with python 3.8

### ISSUE THREAD

**Issue by tngTUDOR** [polca/premise#62]
## Current
A python 3.8 environment allows to install with **pip only dependencies** `premise>=0.4,<1.0.0`, but the tests won't pass.

## Expedted
If premise is intended to be used with `python>=3.9` only, then it should declare it so that it cannot be installed in `python<3.9`.

```
> pytest -k ecoinvent                                                                         
============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.8.12, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/polka-dot/premise, configfile: pytest.ini, testpaths: tests
plugins: cov-3.0.0
collected 5 items / 4 errors / 2 deselected                                                                                                                                                                      

===================================================================================================== ERRORS =====================================================================================================
__________________________________________________________________________________ ERROR collecting tests/test_activity_maps.py __________________________________________________________________________________
tests/test_activity_maps.py:2: in <module>
from premise.activity_maps import InventorySet
premise/__init__.py:9: in <module>
from .ecoinvent_modification import NewDatabase
premise/ecoinvent_modification.py:18: in <module>
from .inventory_imports import (
premise/inventory_imports.py:7: in <module>
import carculator
../../../miniconda3/envs/premise-dev/lib/python3.8/site-packages/carculator/__init__.py:42: in <module>
from .model import CarModel
../../../miniconda3/envs/premise-dev/lib/python3.8/site-packages/carculator/model.py:9: in <module>
from .energy_consumption import EnergyConsumptionModel
../../../miniconda3/envs/premise-dev/lib/python3.8/site-packages/carculator/energy_consumption.py:24: in <module>
class EnergyConsumptionModel:
../../../miniconda3/envs/premise-dev/lib/python3.8/site-packages/carculator/energy_consumption.py:135: in EnergyConsumptionModel
) -> tuple[Union[float, Any], Any, Union[float, Any]]:
E   TypeError: 'type' object is not subscriptable
______________________________________________________________________________________ ERROR collecting tests/test_cars.py _______________________________________________________________________________________
tests/test_cars.py:8: in <module>
from premise import DATA_DIR, NewDatabase
premise/__init__.py:9: in <module>
from .ecoinvent_modification import NewDatabase
premise/ecoinvent_modification.py:18: in <module>
from .inventory_imports import (
premise/inventory_imports.py:7: in <module>
import carculator
../../../miniconda3/envs/premise-dev/lib/python3.8/site-packages/carculator/__init__.py:42: in <module>
from .model import CarModel
../../../miniconda3/envs/premise-dev/lib/python3.8/site-packages/carculator/model.py:9: in <module>
from .energy_consumption import EnergyConsumptionModel
../../../miniconda3/envs/premise-dev/lib/python3.8/site-packages/carculator/energy_consumption.py:24: in <module>
class EnergyConsumptionModel:
../../../miniconda3/envs/premise-dev/lib/python3.8/site-packages/carculator/energy_consumption.py:135: in EnergyConsumptionModel
) -> tuple[Union[float, Any], Any, Union[float, Any]]:
E   TypeError: 'type' object is not subscriptable
___________________________________________________________________________________ ERROR collecting tests/test_electricity.py ___________________________________________________________________________________
tests/test_electricity.py:4: in <module>
from premise import DATA_DIR
premise/__init__.py:9: in <module>
from .ecoinvent_modification import NewDatabase
premise/ecoinvent_modification.py:18: in <module>
from .inventory_imports import (
premise/inventory_imports.py:7: in <module>
import carculator
../../../miniconda3/envs/premise-dev/lib/python3.8/site-packages/carculator/__init__.py:42: in <module>
from .model import CarModel
../../../miniconda3/envs/premise-dev/lib/python3.8/site-packages/carculator/model.py:9: in <module>
from .energy_consumption import EnergyConsumptionModel
../../../miniconda3/envs/premise-dev/lib/python3.8/site-packages/carculator/energy_consumption.py:24: in <module>
class EnergyConsumptionModel:
../../../miniconda3/envs/premise-dev/lib/python3.8/site-packages/carculator/energy_consumption.py:135: in EnergyConsumptionModel
) -> tuple[Union[float, Any], Any, Union[float, Any]]:
E   TypeError: 'type' object is not subscriptable
_______________________________________________________________________________ ERROR collecting tests/test_import_inventories.py ________________________________________________________________________________
tests/test_import_inventories.py:6: in <module>
from premise import DATA_DIR, INVENTORY_DIR
premise/__init__.py:9: in <module>
from .ecoinvent_modification import NewDatabase
premise/ecoinvent_modification.py:18: in <module>
from .inventory_imports import (
premise/inventory_imports.py:7: in <module>
import carculator
../../../miniconda3/envs/premise-dev/lib/python3.8/site-packages/carculator/__init__.py:42: in <module>
from .model import CarModel
../../../miniconda3/envs/premise-dev/lib/python3.8/site-packages/carculator/model.py:9: in <module>
from .energy_consumption import EnergyConsumptionModel
../../../miniconda3/envs/premise-dev/lib/python3.8/site-packages/carculator/energy_consumption.py:24: in <module>
class EnergyConsumptionModel:
../../../miniconda3/envs/premise-dev/lib/python3.8/site-packages/carculator/energy_consumption.py:135: in EnergyConsumptionModel
) -> tuple[Union[float, Any], Any, Union[float, Any]]:
E   TypeError: 'type' object is not subscriptable
```

This is the python 3.9 environment I used to test:

Package                 Version
----------------------- ---------

- appdirs                 1.4.4
- asteval                 0.9.26
- astunparse              1.6.3
- attrs                   21.4.0
- brightway2              2.4.2
- bw-migrations           0.2
- bw2analyzer             0.10
- bw2calc                 1.8.1
- bw2data                 3.6.4
- bw2io                   0.8.6
- bw2parameters           0.7
- carculator              1.6.5
- carculator-truck        0.2.9
- certifi                 2021.10.8
- cffi                    1.15.0
- charset-normalizer      2.0.12
- click                   8.0.4
- constructive-geometries 0.7
- country-converter       0.7.4
- coverage                6.3.2
- cryptography            36.0.1
- cycler                  0.11.0
- docopt                  0.6.2
- eight                   1.0.1
- et-xmlfile              1.1.0
- fasteners               0.17.3
- Flask                   2.0.3
- fonttools               4.29.1
- future                  0.18.2
- idna                    3.3
- iniconfig               1.1.1
- intel-openmp            2022.0.2
- itsdangerous            2.1.0
- Jinja2                  3.0.3
- kiwisolver              1.3.2
- klausen                 0.1.1
- lxml                    4.8.0
- MarkupSafe              2.1.0
- matplotlib              3.5.1
- mkl                     2022.0.2
- mrio-common-metadata    0.2
- numexpr                 2.8.1
- numpy                   1.22.2
- openpyxl                3.0.9
- packaging               21.3
- pandas                  1.4.1
- pathlib                 1.0.1
- peewee                  3.14.9
- Pillow                  9.0.1
- pip                     21.2.4
- pluggy                  1.0.0
- premise                 1.0.3
- premise-gwp             0.5
- prettytable             3.2.0
- psutil                  5.9.0
- py                      1.11.0
- pycountry               22.3.5
- pycparser               2.21
- pypardiso               0.4.0
- pyparsing               3.0.7
- PyPrind                 2.11.3
- pytest                  7.0.1
- pytest-cov              3.0.0
- python-dateutil         2.8.2
- python-json-logger      2.0.2
- pytz                    2021.3
- pyxlsb                  1.0.9
- PyYAML                  6.0
- requests                2.27.1
- scipy                   1.7.0
- setuptools              58.0.4
- six                     1.16.0
- stats-arrays            0.6.5
- tabulate                0.8.9
- tbb                     2021.5.1
- tomli                   2.0.1
- toolz                   0.11.2
- tqdm                    4.63.0
- unicodecsv              0.14.1
- Unidecode               1.3.3
- urllib3                 1.26.8
- voluptuous              0.12.2
- wcwidth                 0.2.5
- Werkzeug                2.0.3
- wheel                   0.37.1
- Whoosh                  2.7.4
- wrapt                   1.13.3
- wurst                   0.3
- xarray                  0.17.0
- xlrd                    2.0.1
- XlsxWriter              3.0.3

**Comment by tngTUDOR** [comment]
All errors seem to come from [carculator](https://github.com/romainsacchi/carculator).

- `../../../miniconda3/envs/premise-dev/lib/python3.8/site-packages/carculator/energy_consumption.py:135: in EnergyConsumptionModel
) -> tuple[Union[float, Any], Any, Union[float, Any]]:
E   TypeError: 'type' object is not subscriptable`

**Comment by tngTUDOR** [comment]
I openned an [issue in carculator ](https://github.com/romainsacchi/carculator/issues/26) to fix this. When a new release of carculator is out, we can maybe close this one.

**Comment by romainsacchi** [comment]
Thanks for that. Should be fixed now.
`premise`>1.0.0 no longer uses directly `carculator`, so the issue should not arise there.
