### ISSUE TITLE
cut-off only?

### ISSUE THREAD

**Issue by simb-sdu** [polca/premise#64]
Hi

the readme mentions support for ecoinvent 3.8 cut-off database. Does this mean that APOS/consequential databases does not work? And what would it require to support these?

**Comment by romainsacchi** [comment]
Hi,
we are working on having `premise` work with the consequential version of ecoinvent.
At least for the building of electricity and fuel markets. We should have a working version in a month or so.
What is needed is to build the logic behind building marginal mixes from the IAM scenario data and to identify supply-constrained suppliers.

**Comment by romainsacchi** [comment]
As for the APOS system model, there is not much interest in pursuing that path it seems, so no plans for that for the moment.
