### ISSUE TITLE
Pruning scenario output files

### ISSUE THREAD

**Issue by marc-vdm** [polca/premise#66]
The current scenario output files are rather large, and I think we can prune quite some rows automagically.

Consider for example the (top of the) below file:
![image](https://user-images.githubusercontent.com/34626062/159533699-c0e38a1a-ed6f-464a-9d6b-49cc7b1d3a77.png)
All values except the last row are the same for all scenario options. In that case we don't need to store them in the file.

Assuming the file I'm looking at here is representative for the average scenario file generated by Premise, we could drop ~200k of the ~500k lines (in this exact case 208467 of the 510172 lines). Assuming this scales linearly, dropping ~40% of the data could reduce file size by ~40%. Reducing file size can speed up imports of these files into AB, I think many users would be quite happy with 40% faster loading times.

Assuming you're exporting through a Pandas DF (haven't checked your code), writing something that checks for non-changed lines should not be too difficult.

**Comment by simb-sdu** [comment]
Hi Marc. a bvit off topic, but how are you able to export so mine lines? i get an error that i exceed max lines (about 200k)

**Comment by marc-vdm** [comment]
Sorry, received these files from someone else, I didn't make them. Perhaps reach out to [support](https://github.com/polca/premise#support) for help with premise problems.

**Comment by simb-sdu** [comment]
Thank you, I will contact the support

**Comment by romainsacchi** [comment]
Hi @simb-sdu @marc-vdm , this issue should now be fixed with #69, leading to the release of v1.0.8 on pip/conda.
There were indeed duplicate rows exported in the scenario difference file. There was also an issue of a blank row instead of the headers, as signalled in  #68 .
