### ISSUE TITLE
Superstructure scenario-diff-file: first row is empty

### ISSUE THREAD

**Issue by CHarpprecht** [polca/premise#68]
The first row in the scenario difference file for the superstructure is just empty, the actual headers are in the second row, while they should be in the second row: 

![grafik](https://user-images.githubusercontent.com/47253039/160643871-94d716d6-babd-4a81-a08d-2aea76d7efb3.png)

The activity browser then throws an error as it cannot find the right headers in the first row of the excel file. 

Current workaround: the user has to delete the first row manually in the excel file.

**Comment by romainsacchi** [comment]
Hi, this is now fixed in #69, leading to v.1.0.8 in pypi/conda, along with the other issue of having duplicate rows.

**Comment by CHarpprecht** [comment]
Wonderful, thank you! :)
