### ISSUE TITLE
Error with SimaPro export

### ISSUE THREAD

**Issue by MaximeAgez** [polca/premise#71]
Hello,

I generated a version of ecoinvent SSP2-RCP19 and could download through brightway2 in activity-browser without any issue, but when I tried to export to SimaPro I get an error.

![image](https://user-images.githubusercontent.com/24285636/170762353-32d4098d-0c3a-471d-af37-44c738b86f29.png)

In case it's useful, I integrated IAM projections within my database though .update_all()

I'm using premise v1.1.4 & brightway2.2.4

I'll update to premise 1.1.7 to check if the bug still occurs and edit my post.

**Comment by romainsacchi** [comment]
Hi @MaximeAgez ,
the issue should be gone now with v.1.2.0.
Have a try and let me know.

We also just opened a discussion group here: https://groups.io/g/premise
