### ISSUE TITLE
Unable to import premise

### ISSUE THREAD

**Issue by ar-ali** [polca/premise#72]
Hi,

I am unable to import premise. Please find the screenshot attached. Can someone please help?

Abdur
![Capture](https://user-images.githubusercontent.com/75308720/177525884-f6c53b30-aed2-43f9-a177-2d6417ba5015.JPG)

**Comment by tngTUDOR** [comment]
Hi @ar-ali , can you please provide a bit more information of your environment. For example, python version, premise version.
Since it appears that you might be using Anaconda, maybe you could provide the output of:
(in your LCALAB environment)
```
conda info
```

```
conda list
```

**Comment by tngTUDOR** [comment]
I can see that there was an [issue](https://github.com/polca/premise/issues/62) with the same error message.
It used to arrive with python 3.8 and premise < 1.0

**Comment by ar-ali** [comment]
I have python 3.9.12 and premise 1.0.8
![1](https://user-images.githubusercontent.com/75308720/177542054-dc5f4cc9-9979-4ea7-ac62-532760be0446.JPG)
![2](https://user-images.githubusercontent.com/75308720/177542059-ef38544f-c469-4d14-a5df-e8141245c173.JPG)

**Comment by tngTUDOR** [comment]
I'm unable to reproduce the error you get (because I don't have a windows machine available at the moment to test). On a Linux install, it works fine for me with both, premise 1.0.8 and 1.1.8 . 

Have you tried to update premise ? for example with:

```
pip install -U premise
```

also, you might want to update pip and conda.

```
pip install -U pip
```

```
conda update -n base -c defaults conda
```

**Comment by ar-ali** [comment]
Thank you, I created a new environment, and it seems to be working.
