### ISSUE TITLE
Scenario correspondence in REMIND: 'SSP2-PkBudg1150' and 'SSP2-PkBudg500' vs. 'SSP2-PkBudg1300', 'SSP2-PkBudg900',

### ISSUE THREAD

**Issue by xiaoshir** [polca/premise#76]
It looks like for REMIND scenarios, the current latest version of premise (1.2.4) supports two new scenarios ('SSP2-PkBudg1150', 'SSP2-PkBudg500') than the old ones ('SSP2-PkBudg1300', 'SSP2-PkBudg900) included in the previous versions. 

Does 'SSP2-PkBudg1150' correspond to 'SSP2-PkBudg1300' in terms of being comparable to 'SSP2-RCP26' in IMAGE?
Similarly, for 'SSP2-PkBudg 500', does it correspond to 'SSP2-PkBud900' in terms of being comparable to 'SSP2-RCP19' in IMAGE?

For documentation, I guess [here](https://premise.readthedocs.io/en/latest/introduction.html#workflow) needs to be updated.
Similar for the [example notebook](https://github.com/polca/premise/blob/master/examples/examples.ipynb) under **List of available scenarios** as well.

**Comment by romainsacchi** [comment]
Hi @xiaoshir,

actually, the old scenarios are no longer available. It is described here: https://premise.readthedocs.io/en/latest/extract.html#current-iam-scenarios

I update the examples notebook, thanks.

Yes, PkBudg1150 corresponds to a RCP of 2.6, and PkBudg500 corresponds to a RCP of 1.9. As for the Baseline, one should use SSP2-NDC, not SSP2-Base (which is worst case, heading for +3.5C by 2100).
