### ISSUE TITLE
Getting the state of our NewDataBase object

### ISSUE THREAD

**Issue by pathiran22** [polca/premise#89]
Hello,
Are there convenient methods to get information about the state of our NewDataBase object ?
For instance, what are the scenarios, what has already been updated or not, etc. ?

**Comment by romainsacchi** [comment]
In `1.5.0-beta`, a `generate_change_report()` method of the `NewDatabase` object, which can be called any time, creates a spreadsheet "log" report summarizing the changes made to the database. This is a way to check what has, or has not yet been done on the database.
