### ISSUE TITLE
requirements include testing packages

### ISSUE THREAD

**Issue by tngTUDOR** [polca/premise#9]
AS with issue #8 , the requirements in the `setup.py` include coveralls and pytest.
I suggest you remove the testing packages in the requirements to slim the amount of packages necessary when installing rmnd-lca.

**Comment by tngTUDOR** [comment]
Per [setuptools documentation](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies), one could use extras to declare the "test" or "dev" dependencies:

> Setuptools allows you to declare dependencies that only get installed under specific circumstances. These dependencies are specified with extras_require keyword and are only installed if another package depends on it (either directly or indirectly) This makes it convenient to declare dependencies for ancillary functions such as “tests” and “docs”.

**Comment by romainsacchi** [comment]
That should be fixed now, thanks.
