### ISSUE TITLE
No brightway2 package found in proven version of premise 1.3.9

### ISSUE THREAD

**Issue by Shima-Fa** [polca/premise#90]
Hi again, @cmutel @romainsacchi 

after installing the 1.3.9 version, it seems like brightway2 package is not included . Since I was working with brightway2 projects , and I checked the package repository for any compatible update with premise or substitution with other packages and I could not find anything, I was wondering will the brightway2 be included in next updates of premsie again, or should I install it separately from now on?

 if yes, would you please inform me of its latest compatible version with premise 1.3.9 with installed ecoinvent 3.9 ? 
 
 Thank you!

**Comment by romainsacchi** [comment]
Hi, 
Yes,, this is normal as only bw2io and bw2data are needed by premise.
You can always install the whole Brightway framework afterwards.

**Comment by Shima-Fa** [comment]
@romainsacchi , Thank you!
