### ISSUE TITLE
EN15804 cut-off database supported?

### ISSUE THREAD

**Issue by simb-sdu** [polca/premise#99]
Hi

Since 3.7, ecoinvent released a cut-off version, that has some cut-off points adjusted slightly as to cmoply with end-of-waste criteria stated by the EN15804 standard (sustainabliltiy for construction works)

Will premise work out of the box with en15804cut-off version of ecoinvent?

**Comment by romainsacchi** [comment]
Hi, I will have a look at it and see what the differences w.r.t. the cutoff version are.

**Comment by simb-sdu** [comment]
Great, thanks Romain.

There is some info on https://ecoinvent.org/the-ecoinvent-database/system-models/ 

note that figure 1 and 2 are a bit unpaedagocial - it is the same model but with a different graphical representation, so it is a bit tricky to see the difference - but the difference is i.e. the position of the cutoff point

**Comment by romainsacchi** [comment]
Hi @simb-sdu,

`1.5.0-beta2` should now be able to handle ecoinvent EN15804 -- tested it with ecoinvent 3.9.
After upgrading, you need to `clear_cache`.
